{% set name = "optuna-integration" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da6100dda2ef6a27f81b3552b03d1f9465a3580f0e767b203fc134f438a46fcf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=61.1.0
    - pip
  run:
    - python >=3.6
    - optuna

test:
  imports:
    - optuna_integration
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://optuna.org/
  summary: An integration module of Optuna
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://optuna-integration.readthedocs.io
  dev_url: https://github.com/optuna/optuna-integration

extra:
  recipe-maintainers:
    - HideakiImamura
    - c-bata
    - contramundum53
    - gen740
    - knshnb
    - not522
    - toshihikoyanase
